name: Build Windows App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    defaults:
      run:
        working-directory: ./src/ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build Electron App
        run: bun run dist:win

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: winstro-windows-installer
          path: src/ui/release/*.exe
          retention-days: 7
